import React, { createContext, useContext, useState, useEffect } from 'react';

export type LanguageCode = 'en' | 'hi' | 'pa' | 'es' | 'fr' | 'ar';

export interface LanguageOption {
  code: LanguageCode;
  name: string;
  nativeName: string;
  flag: string;
}

export const SUPPORTED_LANGUAGES: LanguageOption[] = [
  { code: 'en', name: 'English', nativeName: 'English', flag: '🇬🇧' },
  { code: 'hi', name: 'Hindi', nativeName: 'हिन्दी', flag: '🇮🇳' },
  { code: 'pa', name: 'Punjabi', nativeName: 'ਪੰਜਾਬੀ', flag: '🇮🇳' },
  { code: 'es', name: 'Spanish', nativeName: 'Español', flag: '🇪🇸' },
  { code: 'fr', name: 'French', nativeName: 'Français', flag: '🇫🇷' },
  { code: 'ar', name: 'Arabic', nativeName: 'العربية', flag: '🇦🇪' },
];

export const TRANSLATIONS: Record<LanguageCode, Record<string, string>> = {
  en: {
    hospitalName: 'SGT Hospital',
    tagline: 'Better Health. Brighter Tomorrow.',
    home: 'Home',
    doctors: 'Doctors',
    appointments: 'Appointments',
    records: 'Medical Records',
    medicines: 'Medicines',
    tools: 'Health Tools',
    teleconsult: 'Teleconsultation',
    about: 'About',
    adminPanel: 'Admin Panel',
    searchPlaceholder: 'Search doctors, specialties...',
    emergencyHotline: 'Emergency: 112',
    bookAppointment: 'Book an Appointment',
    exploreServices: 'Explore Our Services',
    heroBadge: 'Your Health, Our Priority',
    heroTitle: 'Advanced Healthcare for a Healthier You',
    heroSubtitle: 'Access the best doctors, manage your medical records, book appointments, and get AI-powered health assistance — all in one place.',
    aiCopilot: 'AI Health Copilot',
    askCopilotPlaceholder: 'Ask about your health, reports, medicines...',
    dailyHealthTips: 'Daily Health Tip',
    findDoctors: 'Find Doctors',
    findDoctorsDesc: 'Top specialists, trusted care',
    bookAppointmentDesc: 'Quick & easy booking',
    medicalRecordsDesc: 'Your health, your data',
    medicinesDesc: 'Order & refill online',
    healthMonitoring: 'Health Monitoring',
    healthMonitoringDesc: 'Track your wellness',
    emergency: 'Emergency',
    emergencyDesc: '24/7 immediate trauma support',
    addressLabel: 'SGT Hospital Campus',
    hospitalAddress: 'Sgt hospital,budhera, Gurugram-Badli Road, Gurugram, Haryana 122505, India',
    contactNumbers: '+91-124-2278187, +91 93193 98632',
    officialEmail: 'medicalsupdt@sgtuniversity.org',
    patientPortal: 'Patient Portal',
    needEmergencyHelp: 'Need Emergency Help?',
    callEmergencyButton: '☎ Call Emergency (112)',
    allRightsReserved: 'All rights reserved. SGT Hospital Healthcare & Research Institute.',
    cancelAppointment: 'Cancel Appointment',
    reschedule: 'Reschedule',
    uploadRecord: 'Upload External Record',
    quickNavigation: 'Quick Navigation',
    specialties: 'Clinical Specialties',
    adminDashboard: 'Hospital Administration Panel',
    managePatients: 'Manage Patients',
    manageDoctors: 'Manage Doctors',
    manageAppointments: 'Manage Appointments',
    manageSalaries: 'Staff Salaries',
    manageExpenses: 'Hospital Expenses',
    hospitalOverview: 'Overview',
    totalPatients: 'Total Patients',
    totalDoctors: 'Total Doctors',
    monthlyBudget: 'Monthly Outflow',
    bedOccupancy: 'Bed Occupancy',
  },
  hi: {
    hospitalName: 'एसजीटी अस्पताल',
    tagline: 'बेहतर स्वास्थ्य। उज्जवल भविष्य।',
    home: 'होम',
    doctors: 'डॉक्टर्स',
    appointments: 'अपॉइंटमेंट्स',
    records: 'मेडिकल रिकॉर्ड्स',
    medicines: 'दवाइयाँ',
    tools: 'स्वास्थ्य उपकरण',
    teleconsult: 'टेलीकंसल्टेशन',
    about: 'परिचय',
    adminPanel: 'एडमिन पैनल',
    searchPlaceholder: 'डॉक्टर, विशेषता खोजें...',
    emergencyHotline: 'आपातकालीन: 112',
    bookAppointment: 'अपॉइंटमेंट बुक करें',
    exploreServices: 'हमारी सेवाएँ देखें',
    heroBadge: 'आपका स्वास्थ्य, हमारी प्राथमिकता',
    heroTitle: 'एक स्वस्थ जीवन के लिए उन्नत स्वास्थ्य सेवा',
    heroSubtitle: 'सर्वश्रेष्ठ डॉक्टरों से परामर्श लें, अपने मेडिकल रिकॉर्ड संभालें, अपॉइंटमेंट बुक करें और एआई स्वास्थ्य सहायता प्राप्त करें — सब कुछ एक ही स्थान पर।',
    aiCopilot: 'एआई हेल्थ कोपायलट',
    askCopilotPlaceholder: 'स्वास्थ्य, रिपोर्ट, दवाइयों के बारे में पूछें...',
    dailyHealthTips: 'दैनिक स्वास्थ्य सुझाव',
    findDoctors: 'डॉक्टर खोजें',
    findDoctorsDesc: 'शीर्ष विशेषज्ञ, विश्वसनीय देखभाल',
    bookAppointmentDesc: 'त्वरित एवं आसान बुकिंग',
    medicalRecordsDesc: 'आपका स्वास्थ्य, आपका डेटा',
    medicinesDesc: 'ऑनलाइन ऑर्डर और रिफिल',
    healthMonitoring: 'स्वास्थ्य निगरानी',
    healthMonitoringDesc: 'अपनी सेहत पर नज़र रखें',
    emergency: 'आपातकालीन',
    emergencyDesc: '24/7 तत्काल ट्रॉमा सहायता',
    addressLabel: 'एसजीटी अस्पताल परिसर',
    hospitalAddress: 'एसजीटी अस्पताल, बुढेड़ा, गुरुग्राम-बादली रोड, गुरुग्राम, हरियाणा 122505, भारत',
    contactNumbers: '+91-124-2278187, +91 93193 98632',
    officialEmail: 'medicalsupdt@sgtuniversity.org',
    patientPortal: 'मरीज़ पोर्टल',
    needEmergencyHelp: 'क्या आपातकालीन सहायता चाहिए?',
    callEmergencyButton: '☎ आपातकालीन कॉल (112)',
    allRightsReserved: 'सर्वाधिकार सुरक्षित। एसजीटी अस्पताल स्वास्थ्य एवं अनुसंधान संस्थान।',
    cancelAppointment: 'अपॉइंटमेंट रद्द करें',
    reschedule: 'पुनर्निर्धारित करें',
    uploadRecord: 'बाहरी रिकॉर्ड अपलोड करें',
    quickNavigation: 'त्वरित नेविगेशन',
    specialties: 'विशेषज्ञ विभाग',
    adminDashboard: 'अस्पताल प्रशासन पैनल',
    managePatients: 'मरीज़ प्रबंधन',
    manageDoctors: 'डॉक्टर प्रबंधन',
    manageAppointments: 'अपॉइंटमेंट प्रबंधन',
    manageSalaries: 'कर्मचारी वेतन',
    manageExpenses: 'अस्पताल खर्च',
    hospitalOverview: 'अवलोकन',
    totalPatients: 'कुल मरीज़',
    totalDoctors: 'कुल डॉक्टर्स',
    monthlyBudget: 'मासिक व्यय',
    bedOccupancy: 'बेड ऑक्यूपेंसी',
  },
  pa: {
    hospitalName: 'ਐਸਜੀਟੀ ਹਸਪਤਾਲ',
    tagline: 'ਬਿਹਤਰ ਸਿਹਤ। ਸੁਨਹਿਰੀ ਭਵਿੱਖ।',
    home: 'ਮੁੱਖ ਪੰਨਾ',
    doctors: 'ਡਾਕਟਰ',
    appointments: 'ਮੁਲਾਕਾਤਾਂ',
    records: 'ਮੈਡੀਕਲ ਰਿਕਾਰਡ',
    medicines: 'ਦਵਾਈਆਂ',
    tools: 'ਸਿਹਤ ਸੰਦ',
    teleconsult: 'ਟੈਲੀਕੰਸਲਟੇਸ਼ਨ',
    about: 'ਸਾਡੇ ਬਾਰੇ',
    adminPanel: 'ਐਡਮਿਨ ਪੈਨਲ',
    searchPlaceholder: 'ਡਾਕਟਰ ਜਾਂ ਬਿਮਾਰੀ ਖੋਜੋ...',
    emergencyHotline: 'ਐਮਰਜੈਂਸੀ: 112',
    bookAppointment: 'ਮੁਲਾਕਾਤ ਬੁੱਕ ਕਰੋ',
    exploreServices: 'ਸਾਡੀਆਂ ਸੇਵਾਵਾਂ ਦੇਖੋ',
    heroBadge: 'ਤੁਹਾਡੀ ਸਿਹਤ, ਸਾਡੀ ਪਹਿਲ',
    heroTitle: 'ਇੱਕ ਤੰਦਰੁਸਤ ਕੱਲ੍ਹ ਲਈ ਉੱਨਤ ਸਿਹਤ ਸੰਭਾਲ',
    heroSubtitle: 'ਵਧੀਆ ਡਾਕਟਰਾਂ ਤੱਕ ਪਹੁੰਚ, ਆਪਣੇ ਮੈਡੀਕਲ ਰਿਕਾਰਡ ਸੰਭਾਲੋ ਅਤੇ ਏਆਈ ਸਹਾਇਤਾ ਪ੍ਰਾਪਤ ਕਰੋ — ਸਭ ਇੱਕੋ ਥਾਂ।',
    aiCopilot: 'ਏਆਈ ਹੈਲਥ ਕੋਪਾਇਲਟ',
    askCopilotPlaceholder: 'ਆਪਣੀ ਸਿਹਤ, ਰਿਪੋਰਟਾਂ ਬਾਰੇ ਪੁੱਛੋ...',
    dailyHealthTips: 'ਰੋਜ਼ਾਨਾ ਸਿਹਤ ਸੁਝਾਅ',
    findDoctors: 'ਡਾਕਟਰ ਲੱਭੋ',
    findDoctorsDesc: 'ਉੱਚ ਮਾਹਰ, ਭਰੋਸੇਯੋਗ ਦੇਖਭਾਲ',
    bookAppointmentDesc: 'ਤੇਜ਼ ਅਤੇ ਆਸਾਨ ਬੁਕਿੰਗ',
    medicalRecordsDesc: 'ਤੁਹਾਡੀ ਸਿਹਤ, ਤੁਹਾਡਾ ਡੇਟਾ',
    medicinesDesc: 'ਆਨਲਾਈਨ ਆਰਡਰ ਅਤੇ ਰੀਫਿਲ',
    healthMonitoring: 'ਸਿਹਤ ਨਿਗਰਾਨੀ',
    healthMonitoringDesc: 'ਤੰਦਰੁਸਤੀ ਟ੍ਰੈਕ ਕਰੋ',
    emergency: 'ਐਮਰਜੈਂਸੀ',
    emergencyDesc: '24/7 ਤੁਰੰਤ ਸਹਾਇਤਾ',
    addressLabel: 'ਐਸਜੀਟੀ ਹਸਪਤਾਲ ਕੈਂਪਸ',
    hospitalAddress: 'ਐਸਜੀਟੀ ਹਸਪਤਾਲ, ਬੁਢੇੜਾ, ਗੁਰੂਗ੍ਰਾਮ-ਬਾਦਲੀ ਰੋਡ, ਗੁਰੂਗ੍ਰਾਮ, ਹਰਿਆਣਾ 122505, ਭਾਰਤ',
    contactNumbers: '+91-124-2278187, +91 93193 98632',
    officialEmail: 'medicalsupdt@sgtuniversity.org',
    patientPortal: 'ਮਰੀਜ਼ ਪੋਰਟਲ',
    needEmergencyHelp: 'ਕੀ ਐਮਰਜੈਂਸੀ ਮਦਦ ਦੀ ਲੋੜ ਹੈ?',
    callEmergencyButton: '☎ ਐਮਰਜੈਂਸੀ ਕਾਲ (112)',
    allRightsReserved: 'ਸਾਰੇ ਹੱਕ ਰਾਖਵੇਂ ਹਨ। ਐਸਜੀਟੀ ਹਸਪਤਾਲ।',
    cancelAppointment: 'ਮੁਲਾਕਾਤ ਰੱਦ ਕਰੋ',
    reschedule: 'ਮੁੜ ਤੈਅ ਕਰੋ',
    uploadRecord: 'ਫਾਈਲ ਅਪਲੋਡ ਕਰੋ',
    quickNavigation: 'ਨੇਵੀਗੇਸ਼ਨ',
    specialties: 'ਵਿਸ਼ੇਸ਼ ਵਿਭਾਗ',
    adminDashboard: 'ਹਸਪਤਾਲ ਪ੍ਰਬੰਧਨ ਪੈਨਲ',
    managePatients: 'ਮਰੀਜ਼ ਪ੍ਰਬੰਧਨ',
    manageDoctors: 'ਡਾਕਟਰ ਪ੍ਰਬੰਧਨ',
    manageAppointments: 'ਮੁਲਾਕਾਤਾਂ ਪ੍ਰਬੰਧਨ',
    manageSalaries: 'ਤਨਖਾਹਾਂ',
    manageExpenses: 'ਹਸਪਤਾਲ ਖਰਚੇ',
    hospitalOverview: 'ਸੰਖੇਪ',
    totalPatients: 'ਕੁੱਲ ਮਰੀਜ਼',
    totalDoctors: 'ਕੁੱਲ ਡਾਕਟਰ',
    monthlyBudget: 'ਮਾਸਿਕ ਖਰਚਾ',
    bedOccupancy: 'ਬੈੱਡ ਵਰਤੋਂ',
  },
  es: {
    hospitalName: 'Hospital SGT',
    tagline: 'Mejor Salud. Futuro Más Brillante.',
    home: 'Inicio',
    doctors: 'Médicos',
    appointments: 'Citas',
    records: 'Historial Médico',
    medicines: 'Medicamentos',
    tools: 'Herramientas',
    teleconsult: 'Telemedicina',
    about: 'Nosotros',
    adminPanel: 'Panel de Admin',
    searchPlaceholder: 'Buscar médicos, especialidades...',
    emergencyHotline: 'Emergencias: 112',
    bookAppointment: 'Reservar Cita',
    exploreServices: 'Explorar Servicios',
    heroBadge: 'Su Salud, Nuestra Prioridad',
    heroTitle: 'Atención Médica Avanzada para Usted',
    heroSubtitle: 'Acceda a los mejores especialistas, gestione su historial clínico y reciba asistencia de IA.',
    aiCopilot: 'Copiloto de Salud IA',
    askCopilotPlaceholder: 'Consulte sobre su salud, informes...',
    dailyHealthTips: 'Consejo de Salud Diario',
    findDoctors: 'Buscar Médicos',
    findDoctorsDesc: 'Especialistas de primer nivel',
    bookAppointmentDesc: 'Reserva rápida y fácil',
    medicalRecordsDesc: 'Su salud, sus datos',
    medicinesDesc: 'Pedidos y recetas en línea',
    healthMonitoring: 'Monitoreo de Salud',
    healthMonitoringDesc: 'Supervise su bienestar',
    emergency: 'Emergencias',
    emergencyDesc: 'Atención inmediata 24/7',
    addressLabel: 'Campus Hospital SGT',
    hospitalAddress: 'Sgt hospital,budhera, Gurugram-Badli Road, Gurugram, Haryana 122505, India',
    contactNumbers: '+91-124-2278187, +91 93193 98632',
    officialEmail: 'medicalsupdt@sgtuniversity.org',
    patientPortal: 'Portal del Paciente',
    needEmergencyHelp: '¿Necesita ayuda urgente?',
    callEmergencyButton: '☎ Llamar a Emergencias (112)',
    allRightsReserved: 'Todos los derechos reservados. Instituto de Salud Hospital SGT.',
    cancelAppointment: 'Cancelar Cita',
    reschedule: 'Reprogramar',
    uploadRecord: 'Subir Registro Externo',
    quickNavigation: 'Navegación Rápida',
    specialties: 'Especialidades Médicas',
    adminDashboard: 'Panel de Administración',
    managePatients: 'Gestión de Pacientes',
    manageDoctors: 'Gestión de Médicos',
    manageAppointments: 'Gestión de Citas',
    manageSalaries: 'Salarios del Personal',
    manageExpenses: 'Gastos del Hospital',
    hospitalOverview: 'Resumen General',
    totalPatients: 'Total Pacientes',
    totalDoctors: 'Total Médicos',
    monthlyBudget: 'Gasto Mensual',
    bedOccupancy: 'Ocupación de Camas',
  },
  fr: {
    hospitalName: 'Hôpital SGT',
    tagline: 'Meilleure Santé. Avenir Plus Brillant.',
    home: 'Accueil',
    doctors: 'Médecins',
    appointments: 'Rendez-vous',
    records: 'Dossiers Médicaux',
    medicines: 'Médicaments',
    tools: 'Outils Santé',
    teleconsult: 'Téléconsultation',
    about: 'À Propos',
    adminPanel: 'Panneau Admin',
    searchPlaceholder: 'Rechercher médecins, spécialités...',
    emergencyHotline: 'Urgence : 112',
    bookAppointment: 'Prendre Rendez-vous',
    exploreServices: 'Découvrir nos Services',
    heroBadge: 'Votre Santé, Notre Priorité',
    heroTitle: 'Des Soins Avancés pour Votre Santé',
    heroSubtitle: 'Consultez les meilleurs spécialistes, gérez vos dossiers médicaux et bénéficiez de l’assistance IA.',
    aiCopilot: 'Copilote Santé IA',
    askCopilotPlaceholder: 'Posez vos questions sur vos rapports...',
    dailyHealthTips: 'Conseil Santé du Jour',
    findDoctors: 'Trouver un Médecin',
    findDoctorsDesc: 'Spécialistes reconnus',
    bookAppointmentDesc: 'Réservation simple et rapide',
    medicalRecordsDesc: 'Votre santé, vos données',
    medicinesDesc: 'Commandes et renouvellements',
    healthMonitoring: 'Suivi de Santé',
    healthMonitoringDesc: 'Surveillez votre bien-être',
    emergency: 'Urgence',
    emergencyDesc: 'Support traumatologique 24/7',
    addressLabel: 'Campus Hôpital SGT',
    hospitalAddress: 'Sgt hospital,budhera, Gurugram-Badli Road, Gurugram, Haryana 122505, Inde',
    contactNumbers: '+91-124-2278187, +91 93193 98632',
    officialEmail: 'medicalsupdt@sgtuniversity.org',
    patientPortal: 'Portail Patient',
    needEmergencyHelp: 'Besoin d’aide urgente ?',
    callEmergencyButton: '☎ Appeler les Urgences (112)',
    allRightsReserved: 'Tous droits réservés. Hôpital et Institut de Recherche SGT.',
    cancelAppointment: 'Annuler le Rendez-vous',
    reschedule: 'Reprogrammer',
    uploadRecord: 'Importer un Document',
    quickNavigation: 'Navigation Rapide',
    specialties: 'Spécialités Cliniques',
    adminDashboard: 'Panneau d’Administration',
    managePatients: 'Gérer les Patients',
    manageDoctors: 'Gérer les Médecins',
    manageAppointments: 'Gérer les Rendez-vous',
    manageSalaries: 'Salaires du Personnel',
    manageExpenses: 'Dépenses Hospitalières',
    hospitalOverview: 'Vue d’Ensemble',
    totalPatients: 'Total Patients',
    totalDoctors: 'Total Médecins',
    monthlyBudget: 'Budget Mensuel',
    bedOccupancy: 'Taux d’Occupation',
  },
  ar: {
    hospitalName: 'مستشفى SGT',
    tagline: 'صحة أفضل. غد مشرق.',
    home: 'الرئيسية',
    doctors: 'الأطباء',
    appointments: 'المواعيد',
    records: 'السجلات الطبية',
    medicines: 'الأدوية',
    tools: 'أدوات الصحة',
    teleconsult: 'الاستشارة المرئية',
    about: 'من نحن',
    adminPanel: 'لوحة التحكم',
    searchPlaceholder: 'ابحث عن طبيب أو تخصص...',
    emergencyHotline: 'طوارئ: 112',
    bookAppointment: 'حجز موعد',
    exploreServices: 'استكشف خدماتنا',
    heroBadge: 'صحتك، أولويتنا القصوى',
    heroTitle: 'رعاية صحية متقدمة من أجلك',
    heroSubtitle: 'تواصل مع أفضل الاستشاريين، وأدر سجلاتك الطبية بمساعدة الذكاء الاصطناعي.',
    aiCopilot: 'مساعد الصحة الذكي',
    askCopilotPlaceholder: 'اسأل عن صحتك، تحاليلك، أدويتك...',
    dailyHealthTips: 'نصيحة صحية يومية',
    findDoctors: 'ابحث عن طبيب',
    findDoctorsDesc: 'نخبة من الاستشاريين المعتمدين',
    bookAppointmentDesc: 'حجز سريع وسهل',
    medicalRecordsDesc: 'صحتك، بياناتك الموثقة',
    medicinesDesc: 'طلب وتجديد الوصفات',
    healthMonitoring: 'المتابعة الصحية',
    healthMonitoringDesc: 'تتبع مؤشراتك الحيوية',
    emergency: 'الطوارئ',
    emergencyDesc: 'فريق طوارئ 24/7',
    addressLabel: 'مجمع مستشفى SGT',
    hospitalAddress: 'Sgt hospital,budhera, Gurugram-Badli Road, Gurugram, Haryana 122505, India',
    contactNumbers: '+91-124-2278187, +91 93193 98632',
    officialEmail: 'medicalsupdt@sgtuniversity.org',
    patientPortal: 'بوابة المريض',
    needEmergencyHelp: 'هل تحتاج مساعدة عاجلة؟',
    callEmergencyButton: '☎ اتصال بالطوارئ (112)',
    allRightsReserved: 'جميع الحقوق محفوظة. مستشفى ومعهد أبحاث SGT.',
    cancelAppointment: 'إلغاء الموعد',
    reschedule: 'إعادة الجدولة',
    uploadRecord: 'رفع تقرير خارجي',
    quickNavigation: 'التنقل السريع',
    specialties: 'التخصصات الطبية',
    adminDashboard: 'لوحة إدارة المستشفى',
    managePatients: 'إدارة المرضى',
    manageDoctors: 'إدارة الأطباء',
    manageAppointments: 'إدارة المواعيد',
    manageSalaries: 'رواتب الموظفين',
    manageExpenses: 'مصاريف المستشفى',
    hospitalOverview: 'نظرة عامة',
    totalPatients: 'إجمالي المرضى',
    totalDoctors: 'إجمالي الأطباء',
    monthlyBudget: 'المصاريف الشهرية',
    bedOccupancy: 'إشغال الأسرة',
  },
};

interface LanguageContextType {
  language: LanguageCode;
  setLanguage: (lang: LanguageCode) => void;
  t: (key: string) => string;
  languages: LanguageOption[];
}

const LanguageContext = createContext<LanguageContextType>({
  language: 'en',
  setLanguage: () => {},
  t: (key) => key,
  languages: SUPPORTED_LANGUAGES,
});

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<LanguageCode>(() => {
    try {
      const saved = localStorage.getItem('sgt_hospital_lang') as LanguageCode;
      if (saved && TRANSLATIONS[saved]) return saved;
    } catch {}
    return 'en';
  });

  const setLanguage = (lang: LanguageCode) => {
    setLanguageState(lang);
    try {
      localStorage.setItem('sgt_hospital_lang', lang);
    } catch {}
  };

  const t = (key: string): string => {
    return TRANSLATIONS[language]?.[key] || TRANSLATIONS['en']?.[key] || key;
  };

  useEffect(() => {
    // Set RTL direction if Arabic
    if (language === 'ar') {
      document.documentElement.dir = 'rtl';
    } else {
      document.documentElement.dir = 'ltr';
    }
  }, [language]);

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, languages: SUPPORTED_LANGUAGES }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
